version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.6.10-alpine3.11
    steps:
      - checkout
      - run:
          name: Dummy Run
          command: |
            ls -al
            apk add --no-cache git

workflows:
  main:
    jobs:
      - build-and-test
